### PR TITLE
Dev/main

### PR DESCRIPTION
**Pull request by NajibAbuSamra**
Milestone.1

### CODE REVIEW

**Comment by masterFoad** [comment]
There is a connection problem we must fix first.

**Comment by danielzar2710** [comment]
this is ok

**Review by firdos94 — APPROVED** [review]

**Review by masterFoad — CHANGES_REQUESTED** [review]
`harry`
This has been changed, please check:
https://github.com/shalomweiss/mm-system-2017/issues/38

**Comment by NajibAbuSamra** [comment]
@masterFoad who needs to change that?

**Comment by masterFoad** [comment]
@NajibAbuSamra the web, because I changed the servlet to "post" when its dealing with user pictures for security purposes.

**Review by danielzar2710 — APPROVED** [review]

**Comment by danielzar2710** [comment]
@masterFoad you want me to do a post request for each picture?
if yes, then i need to tell you that it will be problematic, because it will make the page load for a lot of time

**Comment by masterFoad** [comment]
@danielzar2710 I thought its more secure, If its not a problem and if get is faster I will change.
Do I?

**Comment by danielzar2710** [comment]
Ok, when i do a post what do you send me back?

**Comment by masterFoad** [comment]
@danielzar2710 It sends the same response as the get, The picture.

**Comment by masterFoad** [comment]
@danielzar2710 Its relatively fast for me to change, If you feels its going to take a lot of time then its easier to change the servlets...

**Review by masterFoad — APPROVED** [review]

**Pull request merged**
